
chutney:
  db-server:
    port: 9360
    base-dir: ./.chutney

spring:
  datasource:
    url: jdbc:h2:tcp://localhost:${chutney.db-server.port}/chutney-ui;SCHEMA=PUBLIC
    username:
    password:
    configuration:
      maximum-pool-size: 5
